/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicOpportunitiesRouteImport } from './routes/api/public/opportunities'
import { Route as ApiPublicPartnersRouteImport } from './routes/api/public/partners'
import { Route as ApiPublicStoreRouteImport } from './routes/api/public/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpportunitiesRoute = ApiPublicOpportunitiesRouteImport.update({
  id: '/api/public/opportunities',
  path: '/api/public/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPartnersRoute = ApiPublicPartnersRouteImport.update({
  id: '/api/public/partners',
  path: '/api/public/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStoreRoute = ApiPublicStoreRouteImport.update({
  id: '/api/public/store',
  path: '/api/public/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/opportunities': typeof ApiPublicOpportunitiesRoute
  '/api/public/partners': typeof ApiPublicPartnersRoute
  '/api/public/store': typeof ApiPublicStoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/opportunities': typeof ApiPublicOpportunitiesRoute
  '/api/public/partners': typeof ApiPublicPartnersRoute
  '/api/public/store': typeof ApiPublicStoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/opportunities': typeof ApiPublicOpportunitiesRoute
  '/api/public/partners': typeof ApiPublicPartnersRoute
  '/api/public/store': typeof ApiPublicStoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/chat'
    | '/api/public/opportunities'
    | '/api/public/partners'
    | '/api/public/store'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/chat'
    | '/api/public/opportunities'
    | '/api/public/partners'
    | '/api/public/store'
  id:
    | '__root__'
    | '/'
    | '/api/public/chat'
    | '/api/public/opportunities'
    | '/api/public/partners'
    | '/api/public/store'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicOpportunitiesRoute: typeof ApiPublicOpportunitiesRoute
  ApiPublicPartnersRoute: typeof ApiPublicPartnersRoute
  ApiPublicStoreRoute: typeof ApiPublicStoreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/opportunities': {
      id: '/api/public/opportunities'
      path: '/api/public/opportunities'
      fullPath: '/api/public/opportunities'
      preLoaderRoute: typeof ApiPublicOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partners': {
      id: '/api/public/partners'
      path: '/api/public/partners'
      fullPath: '/api/public/partners'
      preLoaderRoute: typeof ApiPublicPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/store': {
      id: '/api/public/store'
      path: '/api/public/store'
      fullPath: '/api/public/store'
      preLoaderRoute: typeof ApiPublicStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicOpportunitiesRoute: ApiPublicOpportunitiesRoute,
  ApiPublicPartnersRoute: ApiPublicPartnersRoute,
  ApiPublicStoreRoute: ApiPublicStoreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
